name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Debug: List contents of workspace directory
      - name: Debug Workspace Directory Before Deletion
        run: |
          echo "Listing contents of workspace directory before deleting:"
          dir C:\actions-runner\_work\simple-webapp-flask\simple-webapp-flask

      # Attempt to delete directory (replace '%inputPath%' with the actual path if needed)
      - name: Clean Directory
        run: |
          for i in {1..5}; do
            if rd /s /q "C:\actions-runner\_work\simple-webapp-flask\simple-webapp-flask"; then
              break
            else
              echo "Retrying in 5 seconds..."
              sleep 5
            fi
          done  

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simple-webapp-flask:latest
          push: true

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.0'

      # Set up Kubeconfig
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      # Deploy to Kubernetes
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
